### ISSUE TITLE
`default` values should be within `range` or `values`

### ISSUE THREAD

**Issue by hfrick** [tidymodels/dials#229] opened 2022-04-21 18:29 UTC
via @DavisVaughan 

``` r
library(dials)
#> Loading required package: scales

# Issue: Shouldn't be able to set a default outside the range?
# Default should also always be a valid `value`? Or unknown()?
new_quant_param(
  type = "integer",
  default = 12L,
  values = c(1L, 5L, 10L),
  range = c(1L, 10L),
  inclusive = c(TRUE, TRUE),
  label = c(foo = "Foo")
)
#> Foo (quantitative)
#> Range: [1, 10]
#> Values: 3
```

<sup>Created on 2022-04-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by DavisVaughan** [comment] 2022-04-28 13:05
Duplicate of #153 it seems

**Comment by DavisVaughan** [comment] 2022-04-28 14:07
``` r
library(dials)
#> Loading required package: scales

# Laplace has a range argument but has a hardcoded default
x <- Laplace()
x$range
#> $lower
#> [1] 0
#> 
#> $upper
#> [1] 3
x$default
#> [1] 0

# So if you change the range...
x2 <- range_set(x, c(1, 3))

# You can end up with a default that is out of sync with the range
x2$range
#> $lower
#> [1] 1
#> 
#> $upper
#> [1] 3
x2$default
#> [1] 0

# We also have `range_validate()` which doesn't currently check the `default`
# either

# One option is to add a `default` arg to `range_set()` and all dials parameter
# helper functions and always require that they stay in sync
# range_set(x, c(1, 3), default = 2)
# Laplace(range = c(1, 3), default = 2)

# However, this is a lot of work for one thing, and is honestly a little more
# frustrating to use (because you have to think about the default so much).

# Since `default` is only used in `value_seq()` when `n == 1`, maybe we can
# just remove it?
# - When is `n == 1` used in practice?
```

<sup>Created on 2022-04-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by DavisVaughan** [comment] 2022-04-28 15:25
used here https://github.com/tidymodels/dials/blob/6e63018d797e4b995919cc83627879be0305ebd0/R/aaa_values.R#L143

**Comment by hfrick** [comment] 2022-05-20 16:36
note to self: we decided to deprecate the `default` argument

**Closed** 2022-07-12 09:50 UTC
