### ISSUE TITLE
tune_bayes issue

### ISSUE THREAD

**Issue by amin0511ss** [tidymodels/dials#270] opened 2023-01-27 21:53 UTC
I did a tune_grid to find the best parameters setup for a light GBM fit (bonsai package). I then try to improve upon it by using tune_bayes command and set initial to "tune_grid". the code is below and then the error message is shown further down.

code:
lgbm_tuned <- tune_grid(object = lgbm_workflow,
                        resamples = IndividualData_cv_folds,
                        grid = lgbm_grid,
                        metrics = metric_set(yardstick::rmse),
                        control_grid(verbose = F)
)

set.seed(1432)
lgbm_bayes <- tune_bayes(lgbm_workflow, IndividualData_cv_folds, initial = lgbm_tuned, iter = 6)

The error message:
Gaussian process model:
  Error in `.f()`:
  ! The parameter object contains unknowns.
  ℹ This is an internal error that was detected in the dials package.
    Please report it at <https://github.com/tidymodels/dials/issues> with a [reprex](https://https:/...
Error in `check_gp_failure()`:
! Gaussian process model was not fit.
Run `rlang::last_error()` to see where the error occurred.
✖ Optimization stopped prematurely; returning current results.

> rlang::last_error()
<error/rlang_error>
Error in `check_gp_failure()`:
! Gaussian process model was not fit.
---
Backtrace:
 1. tune::tune_bayes(...)
 2. tune:::tune_bayes.workflow(...)
 3. tune:::tune_bayes_workflow(...)
 4. tune:::check_gp_failure(gp_mod, prev_gp_mod)
Run `rlang::last_trace()` to see the full context.
> rlang::last_trace()
<error/rlang_error>
Error in `check_gp_failure()`:
! Gaussian process model was not fit.
---
Backtrace:
    ▆
 1. ├─tune::tune_bayes(...)
 2. └─tune:::tune_bayes.workflow(...)
 3.   └─tune:::tune_bayes_workflow(...)
 4.     └─tune:::check_gp_failure(gp_mod, prev_gp_mod)
 5.       └─rlang::abort("Gaussian process model was not fit.")

**Comment by hfrick** [comment] 2023-02-07 13:30
Hi @amin0511ss, Thanks for reporting this! Could you post a reproducible example, please? I can't run your example because I'm missing a lot of elements you're using, such as the workflow object and the grid object. 

The [reprex](https://reprex.tidyverse.org/) makes it easy to ensure that your example code is indeed reproducible and has helpful tips for [do's and don'ts](https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html).

**Comment by hfrick** [comment] 2023-02-07 14:40
And a sorta wild guess which may also be a red herring: The error says "! The parameter object contains unknowns." Are you trying to tune over the `mtry` parameter? That, per default, contains an unknown in the range of possible values because the upper limit depends on how many predictors are in the model/data. This parameter needs to be finalized (i.e., the upper limit set) before it can be used to tune.

**Comment by hfrick** [comment] 2023-03-27 09:58
I'm going to close this now, assuming it has been resolved. If not, please open another issue!

**Closed by hfrick** 2023-03-27 09:58 UTC
Labels: reprex
